### ISSUE TITLE
Package requires python(abi) = 3.4

### ISSUE THREAD

**Issue by hroncok** [fedora-python/python34#1]
Ideally, python34 should not provide/require python(abi), so nothing in Fedora can depend on it.
However, `__requires_exclude` does not work, so it requires python(abi).

**Comment by hroncok** [comment]
Same issue for python33.

**Comment by torsava** [comment]
If unpack the rpm sources (fedpkg prep) and grep through them, nowhere in there is contained the string "requires_exclude". Therefore you can set the macro all you want, but nothing inside RPM is using it I think. Maybe there's now a different way to accomplish this?

In any case, I tried to go into tho C code to find out where exactly are the requires generated, but I would have to spend days on that before I got my bearings. I think you'd be best off by asking Florian Festi who maintains RPM both in Fedora and upstream.

**Comment by hroncok** [comment]
I said the `__requires_exclude` thing works for python35 and @torsava asked good question: If you don't use it, does python35 require `python(abi)` at all? So I've checked and it does.

``` shell
# without __requires_exclude
$ rpm -q --requires -p python35-3.5.2-1.fc26.x86_64.rpm | grep abi
python(abi) = 3.5
# with __requires_exclude
$ rpm -q --requires -p python35-3.5.2-1.fc26.x86_64.rpm | grep abi
```

**Comment by hroncok** [comment]
@ffesti could you please help us?

**Comment by ffesti** [comment]
Sorry, I don't have enough context to give a useful answer. What's the overall thing you are trying to do and why does it break the deps?

**Comment by hroncok** [comment]
`python(abi) = 3.4` is added to requires automatically. I want to get rid of if, the documented way to do it is to use set `__requires_exclude` like this:

```
%global __requires_exclude ^python\\(abi\\) = 3\\..$
```

However, the requirement is still there. Note that I've tried simpler regexes as well.

**Comment by ffesti** [comment]
This exclude mechanism is not working the way you are using it. See
http://rpm.org/wiki/PackagerDocs/DependencyGenerator for details. You can exclude some files or directories from the generation of requirements completely. The excludes do not work on the generated relations.

I still have the creeping suspicion that you are not using the provides and requirements in the way they are meant to be used. While such tricks may be necessary for a transition period the long term goal should be having matching Provides and Requires that enforce matching (Python) versions between the interpreter, the modules and the programs.

**Comment by hroncok** [comment]
As for the reasoning: This page is intended for developer purposes only and nothing in Fedora should ever depend on it. Keeping the python(abi) provide is unsafe (as packages with broken deps after python3 rebuild/update would require old python34 instead and nothing would be reported to the maintainer) and thus we don't want it. As this package automatically requires it, it would also have to provide it in order to works.

As for the usage, [Fedora guidelines](https://fedoraproject.org/wiki/Packaging:AutoProvidesAndRequiresFiltering#Filtering_provides_and_requires_after_scanning) explicitly say:

> In addition to preventing rpm from scanning files and directories for automatic dependency generation you can also tell rpm to discard a discovered dependency before it records the dependency in the rpm metadata. Use __requires_exclude and __provides_exclude for this.

The [documentation](http://rpm.org/wiki/PackagerDocs/DependencyGenerator) you've linked says:

> The exclude variants operate on generated dependency strings, for example the following would prevent all typical library requires from being added, regardless of which files they originate from:
> 
> ```
> %define __requires_exclude ^lib.*$
> ```

Either is documentation and guidelines wrong (and it accidentaly worked before for different packages) or it is supposed the work I'm using it.

Nevertheless I'll try to use `%__requires_exclude_from` and see if it workarounds the problem.

**Comment by hroncok** [comment]
```
%global _requires_exlude_from *
```

Does not do anything.

**Comment by ffesti** [comment]
Try 
%global __requires_exclude_from ^.*

Note the double underscore at the start and the regular expression as value.

**Comment by hroncok** [comment]
Yes, my bad, sorry, too quick, without thinking, trying with:

```
%global __requires_exlude_from ^.*
```

**Comment by hroncok** [comment]
Still requires all the stuff.

**Comment by hroncok** [comment]
Ha, python34 and python33 have:

```
# Avoid having various bogus auto-generated Provides lines for the various
# python c modules' SONAMEs:
Source1: find-provides-without-python-sonames.sh
%global _use_internal_dependency_generator 0
%global __find_provides %{SOURCE1}
```

I strongly believe this is the problem. Will try.

**Comment by hroncok** [comment]
@ffesti Thanks for your help.
